import type { ConnectorId } from './types.js';

export const CONNECTOR_CATEGORIES = [
  'AI',
  'Communication',
  'Calendar',
  'Knowledge',
  'Developer Tools',
  'Storage',
  'CRM & Commerce',
  'Media & Social',
] as const;

export type ConnectorCategory = (typeof CONNECTOR_CATEGORIES)[number];
export type ConnectorAvailability = 'available' | 'planned';
export type ConnectorSetupMode = 'oauth' | 'apikey';

export interface ConnectorCatalogEntry {
  id: ConnectorId;
  name: string;
  category: ConnectorCategory;
  description: string;
  setupMode: ConnectorSetupMode;
  availability: ConnectorAvailability;
  ctaLabel: string;
}

export const CONNECTOR_CATALOG = [
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'AI',
    description: 'Files and assistants with API-key setup and immediate ingest.',
    setupMode: 'apikey',
    availability: 'available',
    ctaLabel: 'Add API key',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'AI',
    description: 'Model access roster via API key, ready for future activity ingest.',
    setupMode: 'apikey',
    availability: 'available',
    ctaLabel: 'Add API key',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'AI',
    description: 'Research sessions, threads, and saved discoveries.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'AI',
    description: 'Chats, prompts, uploaded files, and workspace context.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'AI',
    description: 'Models, spaces, datasets, and inference activity.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'Communication',
    description: 'Mail threads, labels, and attachments.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'outlook_mail',
    name: 'Outlook Mail',
    category: 'Communication',
    description: 'Messages, folders, attachments, and threads.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    description: 'Channels, DMs, files, and mentions.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'Communication',
    description: 'Servers, channels, messages, and shared links.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    category: 'Communication',
    description: 'Teams, chats, meetings, and files.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'Communication',
    description: 'Chats, channels, media, and saved messages.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'whatsapp_business',
    name: 'WhatsApp Business',
    category: 'Communication',
    description: 'Business conversations and support threads.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'Communication',
    description: 'Customer conversations, tickets, and contacts.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'Communication',
    description: 'Support tickets, comments, and customer context.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'help_scout',
    name: 'Help Scout',
    category: 'Communication',
    description: 'Support inboxes, threads, and notes.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    category: 'Calendar',
    description: 'Primary calendar events with attendee edges.',
    setupMode: 'oauth',
    availability: 'available',
    ctaLabel: 'Connect',
  },
  {
    id: 'outlook_calendar',
    name: 'Outlook Calendar',
    category: 'Calendar',
    description: 'Meetings, invites, and recurring events.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'Calendar',
    description: 'Booking links, events, invitees, and follow-ups.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'google_tasks',
    name: 'Google Tasks',
    category: 'Calendar',
    description: 'Lists, tasks, due dates, and completion state.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    category: 'Calendar',
    description: 'Projects, tasks, labels, and deadlines.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'Knowledge',
    description: 'Pages and parent relationships via one-click OAuth.',
    setupMode: 'oauth',
    availability: 'available',
    ctaLabel: 'Connect',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Knowledge',
    description: 'Vault notes, links, and tags.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'roam',
    name: 'Roam Research',
    category: 'Knowledge',
    description: 'Pages, blocks, backlinks, and graph references.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'evernote',
    name: 'Evernote',
    category: 'Knowledge',
    description: 'Notebooks, notes, tasks, and attachments.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'Knowledge',
    description: 'Pages, spaces, comments, and mentions.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'coda',
    name: 'Coda',
    category: 'Knowledge',
    description: 'Docs, tables, tasks, and collaborative notes.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'Knowledge',
    description: 'Bases, tables, linked records, and views.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'zotero',
    name: 'Zotero',
    category: 'Knowledge',
    description: 'Library items, authors, tags, and collections.',
    setupMode: 'apikey',
    availability: 'available',
    ctaLabel: 'Add API key',
  },
  {
    id: 'web_clip',
    name: 'Web clipper',
    category: 'Knowledge',
    description: 'Captured pages, highlights, and source URLs.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'bookmarks',
    name: 'Bookmarks',
    category: 'Knowledge',
    description: 'Browser saves, tags, and revisit signals.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Developer Tools',
    description: 'Events, commits, issues, and pull requests.',
    setupMode: 'oauth',
    availability: 'available',
    ctaLabel: 'Connect',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Developer Tools',
    description: 'Repos, merge requests, issues, and pipelines.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    category: 'Developer Tools',
    description: 'Repositories, pull requests, and builds.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'Developer Tools',
    description: 'Issues, projects, cycles, and triage.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'Developer Tools',
    description: 'Issues, epics, sprints, and comments.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'Developer Tools',
    description: 'Projects, tasks, milestones, and comments.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'Developer Tools',
    description: 'Boards, lists, cards, and checklists.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'Developer Tools',
    description: 'Spaces, docs, tasks, and goals.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'Developer Tools',
    description: 'Boards, items, updates, and timelines.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'Developer Tools',
    description: 'Files, comments, prototypes, and design systems.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'Developer Tools',
    description: 'Boards, stickies, diagrams, and brainstorm sessions.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    category: 'Storage',
    description: 'Docs, sheets, slides, PDFs, and folder graphs.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    category: 'Storage',
    description: 'Files, shared folders, and paper docs.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    category: 'Storage',
    description: 'Files, folders, and collaboration links.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'box',
    name: 'Box',
    category: 'Storage',
    description: 'Content, collections, and enterprise documents.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'CRM & Commerce',
    description: 'Contacts, companies, deals, and notes.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'CRM & Commerce',
    description: 'Accounts, opportunities, tasks, and events.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    category: 'CRM & Commerce',
    description: 'Leads, deals, notes, and follow-up tasks.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'CRM & Commerce',
    description: 'Customers, subscriptions, invoices, and payments.',
    setupMode: 'apikey',
    availability: 'planned',
    ctaLabel: 'Add API key',
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'CRM & Commerce',
    description: 'Invoices, vendors, customers, and accounting events.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'CRM & Commerce',
    description: 'Orders, customers, products, and fulfillment.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'x_twitter',
    name: 'X / Twitter',
    category: 'Media & Social',
    description: 'Tweets, replies, bookmarks, and follows.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'Media & Social',
    description: 'Posts, messages, contacts, and profile activity.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    category: 'Media & Social',
    description: 'Posts, comments, saves, and subscribed communities.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Media & Social',
    description: 'Videos, playlists, watch history, and subscriptions.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'Media & Social',
    description: 'Saved tracks, playlists, podcasts, and listening patterns.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'pocket',
    name: 'Pocket',
    category: 'Media & Social',
    description: 'Read-later saves, highlights, and tags.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'instapaper',
    name: 'Instapaper',
    category: 'Media & Social',
    description: 'Saved articles, highlights, and reading progress.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
  {
    id: 'raindrop',
    name: 'Raindrop.io',
    category: 'Media & Social',
    description: 'Bookmarks, collections, annotations, and tags.',
    setupMode: 'oauth',
    availability: 'planned',
    ctaLabel: 'Connect',
  },
] as const satisfies readonly ConnectorCatalogEntry[];

export const IMPLEMENTED_CONNECTOR_IDS = CONNECTOR_CATALOG.filter(
  (connector) => connector.availability === 'available',
).map((connector) => connector.id);
